### ISSUE TITLE
Pennsieve user - canUpdate status incorrect

### ISSUE THREAD

**Issue by alan-wu** [AnatomicMaps/flatmap-server#9]
There is a bug in the code causing canUpdate status of a newly added  user in the team to be incorrect.

The annotation team is cached and never get updated until a server is update -

https://github.com/AnatomicMaps/flatmap-server/blob/5311584628344a7d5bf9e5295d77177015d0398d/mapserver/pennsieve.py#L67

**Comment by dbrnz** [comment]
Fixed in release 0.26.2.
